export const DevSkills: string[] = [
	"React",
	"Angular",
	"TypeScript",
	"Javascript",
	"Remix",
	"Next.js",
	"Node.js",
	"Redux",
	"Zustand",
	"CI/CD",
	"GraphQL",
	"RESTful API design",
	"Prisma",
	"PostgreSQL",
	"database management",
	"security best practices",
	"HTML",
	"CSS",
	"Material-UI",
	"Framer-Motion",
	"Jest",
	"Vitest",
	"Cypress",
	"Playwright",
	"Tailwind CSS",
	"Azure",
	"AWS",
	"AWS CDK",
	"AWS SDK",
	"Docker",
	"VBA",
	"Scrum",
	"Agile",
];
export const UxSkills: string[] = [
	"Figma",
	"AdobeXD",
	"Photoshop",
	"Illustrator",
	"Affinity Designer",
	"Animate",
	"After Effects",
	"Premiere Pro",
	"user tests",
	"wireframes and prototypes",
	"User-Centered-Design",
	"user journey map",
	"personas",
	"accessibility",
	"red routes",
	"card sorting",
	"responsive design",
	"UX writing",
	"UX research",
	"cross-cultural design",
	"ideation workshops",
];
